// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvfisvmvlnufadmykwfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Zmlzdm12bG51ZmFkbXlrd2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDkyNTUsImV4cCI6MjA2NDI4NTI1NX0.1crHHq2sxuXirQi9NV7K2IrRK3KSj5ihT8U-xIbVfFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);